version = 1
SPDX-PackageName = "xdg-thumbnail"

[[annotations]]
path = [
  "**/*.md",
  "**/*.json",
  "**/*.toml",
  "**/*.yaml",
  "**/*.lock",
  ".editorconfig",
  ".gitignore",
  "devenv.lock",
  "devenv.yaml",
  "justfile",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 KIM Hyunjae"
SPDX-License-Identifier = "AGPL-3.0-or-later"
