[package]
name = "xdg-thumbnail-generate"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Generate Freedesktop thumbnail cache entries"

[[bin]]
name = "xdg-thumbnail-generate"
path = "src/main.rs"

[dependencies]
xdg-thumbnail = { path = "../xdg-thumbnail" }
