[package]
name = "xdg-thumbnail-generate"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Generate Freedesktop thumbnail cache entries"

[[bin]]
name = "xdg-thumbnail-generate"
path = "src/main.rs"

[dependencies]
base64.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
freedesktop_entry_parser.workspace = true
mime.workspace = true
serde.workspace = true
serde_json.workspace = true
shell-words.workspace = true
tempfile.workspace = true
xdg-thumbnail = { path = "../xdg-thumbnail" }
xdg-mime.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
png.workspace = true
predicates.workspace = true
serde_json.workspace = true
tempfile.workspace = true
